name: omic_learn
channels:
  - defaults
dependencies:
  - python=3.7
  - py-xgboost=1.3.3
  - pip=21.1.3
  - pip:
      - streamlit==1.0.0
      - pandas==1.3.3
      - numpy==1.21.2
      - scikit-learn==1.0
      - openpyxl==3.0.9
      - plotly==5.3.1
      - kaleido==0.2.1
      - XlsxWriter==3.0.1
      - watchdog==2.1.6
