name: omic_learn
channels:
  - defaults
dependencies:
  - python=3.8
  - py-xgboost=1.3.3
  - pip=21.1.3
  - pip:
      - streamlit==1.8.1
      - pandas==1.4.2
      - numpy==1.22.3
      - scikit-learn==1.0.2
      - openpyxl==3.0.9
      - plotly==5.7.0
      - kaleido==0.2.1
      - XlsxWriter==3.0.1
      - watchdog==2.1.7